# START:dev_config
development:
    adapter: stomp
    login: ""
    passcode: ""
    host: localhost
    port: 61613
    reliable: true
    reconnectDelay: 5
# END:dev_config

test:
    adapter: test
    reliable: false

production:
    adapter: stomp
    reliable: true
    # properties below are all defaults for this adapter
    # login: ""
    # passcode: ""
    # host: localhost
    # port: 61613
    # reliable: true
    # reconnectDelay: 5
